### ISSUE TITLE
karaf_feature : feature:install fail

### ISSUE THREAD

**Issue by Glaglaton** [remyma/ansible-karaf-module#7]
Hello,

I'm using Karaf v4.0.7 and I encounter some problems when I'm trying to use the karaf_feature module.

First, could you confirm me that I can use this module to proceed to the following installation with Ansible (described here https://karaf.apache.org/manual/latest-3.0.x/wrapper).
I would like to execute these 3 actions :
1 - feature:install service-wrapper
2 - feature:install wrapper
3 - wrapper:install

When I execute the following test, i get an empty error from Karaf. Do you have an idea about this problem ?

failed: [XXX] (item=service-wrapper) => {"changed": false, "item": "service-wrapper", "msg": ""}
failed: [XXX] (item=wrapper) => {"changed": false, "item": "wrapper", "msg": ""}

```
- name: Install features
  become: true
  become_user: "{{ user.name }}"
  karaf_feature:
    name: "{{ item }}"
    state: present
    client_bin: "{{ user.home }}/{{ app_name }}/bin/client"
  with_items:
    - service-wrapper
    - wrapper
```

Thank you
